version: '3.1'

services:

  wordpress:
    build:                                            # image: wordpress:latest avec xDebug - config: Dockerfile
      context: ./
      dockerfile: Dockerfile
      args:
        ## ARGS doivent être inclus dans la commande BUILD
        ## car les ARGS sont uniquement disponibles durant le BUILD process
        ## https://docs.docker.com/compose/compose-file/compose-file-v3/#args
        xdebug_remote_host: host.docker.internal
        xdebug_mode: debug                            # develop,debug,profile # https://xdebug.org/docs/all_settings#mode
        xdebug_output_dir: /var/log/xdebug            # https://xdebug.org/docs/all_settings#mode
    container_name: "${PROJECT_NAME}_php"

    environment:
      ## variables ENV propre à l'image wordpress
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_PASSWORD: wordpress
    ports:
      - 80:80
    volumes:
      - ./build:/var/www/html/wp-content/plugins/ized-gutenberg

  #######################################
  ### MYSQL                            ##
  #######################################
  mariadb:
    image: mariadb:latest
    container_name: "${PROJECT_NAME}_mariadb"
    command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON
    volumes:
      - ./_DOCKER/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress